#!/bin/bash

wget https://github.com/alanxz/rabbitmq-c/releases/download/v0.4.1/rabbitmq-c-0.4.1.tar.gz

tar zxvf rabbitmq-c-0.4.1.tar.gz
cp -R debian rabbitmq-c-0.4.1
cp rabbitmq-c-0.4.1.tar.gz librabbitmq_0.4.1.orig.tar.gz
