#!/bin/bash

VERSION="0.5.0"

wget https://github.com/alanxz/rabbitmq-c/releases/download/v${VERSION}/rabbitmq-c-${VERSION}.tar.gz

tar zxvf rabbitmq-c-${VERSION}.tar.gz
cp -R debian rabbitmq-c-${VERSION}
cp rabbitmq-c-${VERSION}.tar.gz librabbitmq_${VERSION}.orig.tar.gz
